### ISSUE TITLE
Rate-limiter should drop requests when the service RPS is larger than 2x of the limit

### ISSUE THREAD

**Issue by ShanniLi** [uber/hyperbahn#17]
Otherwise, Hyperbahn nodes can still be stressed out by responding with error frames.

One thing though, 2x may not be aggressive enough. E.g., if the current rate-limit is 1200, 2x would be 2400, the way out of a node's bandwidth. We may want to use the total limit per node as the threshold for dropping requests.  

cc @Raynos @jcorbin @kriskowal

**Comment by Raynos** [comment]
@ShanniLi 

Math.max(totalRPS, 2* rate) is +1

**Comment by kriskowal** [comment]
We should also consider training the circuit breaker to drop requests silently over a certain rate of declines.

**Comment by ShanniLi** [comment]
@kriskowal The reason to drop requests is that Hyperbahn nodes cannot handle current RPS, i.e., too busy to even return busy frames. I think circuit breaker is fine in this scenario since rate limiter should be enough to handle it.
