### ISSUE TITLE
Rate limiter should clear edge counters that have a zero RPS

### ISSUE THREAD

**Issue by ShanniLi** [uber/hyperbahn#25]
Otherwise, the list is going to keep growing and create an unnecessary overhead.

cc: @Raynos @kriskowal @jcorbin

**Comment by Raynos** [comment]
@ShanniLi great idea :)

**Comment by Raynos** [comment]
@ShanniLi EdgeCounter is a prototype right ? ;)

**Comment by ShanniLi** [comment]
@Raynos live and learn :)
